### PR TITLE
Added gesture recognizers to Google Maps

### PR DESCRIPTION
**Pull request by faithomotoso**
Added gesture recognizers to Google Maps to allow map movement/navigation when package is a child of ScrollView. [#52](https://github.com/fysoul17/google_maps_place_picker/issues/52)

### CODE REVIEW

**Comment by fysoul17** [comment]
Thanks for your contribution. 
Before the merge, can you remove pubspec.lock, please?

**Comment by faithomotoso** [comment]
oh I'm sorry. I'm not so sure how to go about that. Please can you tell me how, I don't want to mess things up

**Comment by fysoul17** [comment]
Thats okay ;) 
You need to do pull request targeting only the file that needs to be changed, not with .gitignore.

Please resubmit it, please. I will close this for now. Also, let me know if you want me to add the code for the case.

**Comment by faithomotoso** [comment]
Yes please add the code. Thanks.

**Pull request closed without merging**
